// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:2265ea5607b492cdd09d723e727b8334c51951be60b0bf6d6ddbe9c9aecfcbf2'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:3cc333ecad9f3f4c7229370a9d2c37e908cdce0f8d2e9fb132d50605b024eff2'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly AppMeta: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Intent: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly tag: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly detail: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly AppMeta: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Intent: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly tag: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly detail: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly appMeta: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly intent: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly detail: CodecTypes['sqlite/text@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly tag: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly appMeta: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly intent: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly detail: CodecTypes['sqlite/text@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly tag: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly appMeta: {
              columns: {
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['key'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly intent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly tag: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly detail: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['status'] }];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly appMeta: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AppMeta';
    };
    readonly intent: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Intent' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly AppMeta: {
            readonly fields: {
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'appMeta';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly key: { readonly column: 'key' };
                readonly value: { readonly column: 'value' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Intent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly tag: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly detail: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'intent';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tag: { readonly column: 'tag' };
                readonly payload: { readonly column: 'payload' };
                readonly status: { readonly column: 'status' };
                readonly detail: { readonly column: 'detail' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
