export {
	RulingAlreadyRuled,
	RulingAlreadySuperseded,
	RulingChoiceUnknown,
	type RulingGateFailure,
	RulingGatePieceMissing,
	RulingNotFound,
	RulingNotRuled,
	type RulingProclaimFailure,
	type RulingReadFailure,
	RulingReclassificationEmpty,
	type RulingReclassifyFailure,
	type RulingRequestFailure,
	RulingSubjectMissing,
	RulingSupersedesItself,
	type RulingSupersessionFailure,
	type RulingVerdictFailure,
} from "#errors.ts";
export type {
	Ruling,
	RulingAnswer,
	RulingAxes,
	RulingChoice,
	RulingChoiceInput,
	RulingGate,
	RulingGateInput,
	RulingProclamation,
	RulingReclassification,
	RulingReclassifyInput,
	RulingRequest,
	RulingRequester,
	RulingSubject,
	RulingSupersedeInput,
	RulingSupersession,
	RulingVerdict,
} from "#model.ts";
export { Rulings, RulingsLive } from "#rulings.ts";
