// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:957d308f4f0887e60dd97056e641a0b6114f5877152e6d8a71df23700f3a33b0'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:3cc333ecad9f3f4c7229370a9d2c37e908cdce0f8d2e9fb132d50605b024eff2'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Agent: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly role: CodecTypes['sqlite/text@1']['output'];
      readonly charter: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly AgentSession: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly agentId: CodecTypes['sqlite/text@1']['output'];
      readonly backend: CodecTypes['sqlite/text@1']['output'];
      readonly cwd: CodecTypes['sqlite/text@1']['output'];
      readonly nativeRef: CodecTypes['sqlite/text@1']['output'] | null;
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly charterDeliveredAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly AppMeta: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Berth: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly agentId: CodecTypes['sqlite/text@1']['output'];
      readonly runner: CodecTypes['sqlite/text@1']['output'];
      readonly source: CodecTypes['sqlite/text@1']['output'];
      readonly slug: CodecTypes['sqlite/text@1']['output'];
      readonly ref: CodecTypes['sqlite/text@1']['output'];
      readonly branch: CodecTypes['sqlite/text@1']['output'];
      readonly path: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly strandedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly Intent: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly tag: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly detail: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly SessionEvent: {
      readonly sessionId: CodecTypes['sqlite/text@1']['output'];
      readonly seq: CodecTypes['sqlite/integer@1']['output'];
      readonly kind: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly at: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Agent: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly role: CodecTypes['sqlite/text@1']['input'];
      readonly charter: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly AgentSession: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly agentId: CodecTypes['sqlite/text@1']['input'];
      readonly backend: CodecTypes['sqlite/text@1']['input'];
      readonly cwd: CodecTypes['sqlite/text@1']['input'];
      readonly nativeRef: CodecTypes['sqlite/text@1']['input'] | null;
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly charterDeliveredAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly AppMeta: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Berth: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly agentId: CodecTypes['sqlite/text@1']['input'];
      readonly runner: CodecTypes['sqlite/text@1']['input'];
      readonly source: CodecTypes['sqlite/text@1']['input'];
      readonly slug: CodecTypes['sqlite/text@1']['input'];
      readonly ref: CodecTypes['sqlite/text@1']['input'];
      readonly branch: CodecTypes['sqlite/text@1']['input'];
      readonly path: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly strandedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly Intent: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly tag: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly detail: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly SessionEvent: {
      readonly sessionId: CodecTypes['sqlite/text@1']['input'];
      readonly seq: CodecTypes['sqlite/integer@1']['input'];
      readonly kind: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly at: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly agent: {
      readonly charter: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly role: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly agentSession: {
      readonly agentId: CodecTypes['sqlite/text@1']['output'];
      readonly backend: CodecTypes['sqlite/text@1']['output'];
      readonly charterDeliveredAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly cwd: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly nativeRef: CodecTypes['sqlite/text@1']['output'] | null;
      readonly status: CodecTypes['sqlite/text@1']['output'];
    };
    readonly appMeta: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly berth: {
      readonly agentId: CodecTypes['sqlite/text@1']['output'];
      readonly branch: CodecTypes['sqlite/text@1']['output'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly path: CodecTypes['sqlite/text@1']['output'];
      readonly ref: CodecTypes['sqlite/text@1']['output'];
      readonly runner: CodecTypes['sqlite/text@1']['output'];
      readonly slug: CodecTypes['sqlite/text@1']['output'];
      readonly source: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly strandedAt: CodecTypes['sqlite/datetime@1']['output'] | null;
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly intent: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      readonly detail: CodecTypes['sqlite/text@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly tag: CodecTypes['sqlite/text@1']['output'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly sessionEvent: {
      readonly at: CodecTypes['sqlite/datetime@1']['output'];
      readonly kind: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly seq: CodecTypes['sqlite/integer@1']['output'];
      readonly sessionId: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly agent: {
      readonly charter: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly role: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly agentSession: {
      readonly agentId: CodecTypes['sqlite/text@1']['input'];
      readonly backend: CodecTypes['sqlite/text@1']['input'];
      readonly charterDeliveredAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly cwd: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly nativeRef: CodecTypes['sqlite/text@1']['input'] | null;
      readonly status: CodecTypes['sqlite/text@1']['input'];
    };
    readonly appMeta: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly berth: {
      readonly agentId: CodecTypes['sqlite/text@1']['input'];
      readonly branch: CodecTypes['sqlite/text@1']['input'];
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly path: CodecTypes['sqlite/text@1']['input'];
      readonly ref: CodecTypes['sqlite/text@1']['input'];
      readonly runner: CodecTypes['sqlite/text@1']['input'];
      readonly slug: CodecTypes['sqlite/text@1']['input'];
      readonly source: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly strandedAt: CodecTypes['sqlite/datetime@1']['input'] | null;
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly intent: {
      readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
      readonly detail: CodecTypes['sqlite/text@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly tag: CodecTypes['sqlite/text@1']['input'];
      readonly updatedAt: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly sessionEvent: {
      readonly at: CodecTypes['sqlite/datetime@1']['input'];
      readonly kind: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly seq: CodecTypes['sqlite/integer@1']['input'];
      readonly sessionId: CodecTypes['sqlite/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly agent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly charter: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['status'] }];
              foreignKeys: readonly [];
            };
            readonly agentSession: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly agentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly backend: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'claude'>;
                  };
                };
                readonly cwd: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly nativeRef: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly charterDeliveredAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['agentId'] }];
              foreignKeys: readonly [];
            };
            readonly appMeta: {
              columns: {
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['key'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly berth: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly agentId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly runner: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly ref: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly branch: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly path: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly strandedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                { readonly columns: readonly ['agentId'] },
                { readonly columns: readonly ['status'] },
              ];
              foreignKeys: readonly [];
            };
            readonly intent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly tag: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly detail: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [{ readonly columns: readonly ['status'] }];
              foreignKeys: readonly [];
            };
            readonly sessionEvent: {
              columns: {
                readonly sessionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly seq: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly kind: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['sessionId', 'seq'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly appMeta: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AppMeta';
    };
    readonly intent: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Intent' };
    readonly agent: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Agent' };
    readonly agentSession: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AgentSession';
    };
    readonly berth: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Berth' };
    readonly sessionEvent: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'SessionEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Agent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly charter: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'agent';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly role: { readonly column: 'role' };
                readonly charter: { readonly column: 'charter' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly AgentSession: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly agentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly backend: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly cwd: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly nativeRef: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly charterDeliveredAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'agentSession';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly agentId: { readonly column: 'agentId' };
                readonly backend: { readonly column: 'backend' };
                readonly cwd: { readonly column: 'cwd' };
                readonly nativeRef: { readonly column: 'nativeRef' };
                readonly status: { readonly column: 'status' };
                readonly charterDeliveredAt: { readonly column: 'charterDeliveredAt' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly AppMeta: {
            readonly fields: {
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'appMeta';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly key: { readonly column: 'key' };
                readonly value: { readonly column: 'value' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Berth: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly agentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly runner: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly ref: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly branch: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly path: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly strandedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'berth';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly agentId: { readonly column: 'agentId' };
                readonly runner: { readonly column: 'runner' };
                readonly source: { readonly column: 'source' };
                readonly slug: { readonly column: 'slug' };
                readonly ref: { readonly column: 'ref' };
                readonly branch: { readonly column: 'branch' };
                readonly path: { readonly column: 'path' };
                readonly status: { readonly column: 'status' };
                readonly strandedAt: { readonly column: 'strandedAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Intent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly tag: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly detail: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'intent';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tag: { readonly column: 'tag' };
                readonly payload: { readonly column: 'payload' };
                readonly status: { readonly column: 'status' };
                readonly detail: { readonly column: 'detail' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly SessionEvent: {
            readonly fields: {
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly seq: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'sessionEvent';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly sessionId: { readonly column: 'sessionId' };
                readonly seq: { readonly column: 'seq' };
                readonly kind: { readonly column: 'kind' };
                readonly payload: { readonly column: 'payload' };
                readonly at: { readonly column: 'at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
