export const RULING_TABLE = {
  tableName: 'ruling',
  contractTable: {
    columns: [
      { name: 'answer', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'answerChoiceId', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'context', typeSql: 'TEXT', defaultSql: '', nullable: false },
      {
        name: 'createdAt',
        typeSql: 'TEXT',
        defaultSql: "DEFAULT (datetime('now'))",
        nullable: false,
      },
      { name: 'deliveredAt', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'id', typeSql: 'TEXT', defaultSql: '', nullable: false },
      { name: 'question', typeSql: 'TEXT', defaultSql: '', nullable: false },
      { name: 'radius', typeSql: 'TEXT', defaultSql: '', nullable: false },
      { name: 'requesterAgentId', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'requesterAuthority', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'ruledAt', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'ruledBy', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'ruledByAgentId', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'rung', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'supersededAt', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'supersededBy', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'supersededById', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'urgency', typeSql: 'TEXT', defaultSql: '', nullable: false },
      { name: 'withdrawnAt', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'withdrawnBy', typeSql: 'TEXT', defaultSql: '', nullable: true },
      { name: 'withdrawnNote', typeSql: 'TEXT', defaultSql: '', nullable: true },
    ],
    primaryKey: { columns: ['id'] },
    uniques: [],
    foreignKeys: [
      {
        columns: ['requesterAgentId'],
        references: { table: 'agent', columns: ['id'] },
        constraint: true,
        onDelete: 'restrict',
        onUpdate: 'restrict',
      },
      {
        columns: ['ruledByAgentId'],
        references: { table: 'agent', columns: ['id'] },
        constraint: true,
        onDelete: 'restrict',
        onUpdate: 'restrict',
      },
      {
        columns: ['answerChoiceId'],
        references: { table: 'rulingChoice', columns: ['id'] },
        constraint: true,
        onDelete: 'restrict',
        onUpdate: 'restrict',
      },
      {
        columns: ['supersededById'],
        references: { table: 'ruling', columns: ['id'] },
        constraint: true,
        onDelete: 'restrict',
        onUpdate: 'restrict',
      },
    ],
  },
  schemaColumnNames: [
    'answer',
    'answerChoiceId',
    'context',
    'createdAt',
    'deliveredAt',
    'id',
    'question',
    'radius',
    'requesterAgentId',
    'requesterAuthority',
    'ruledAt',
    'ruledBy',
    'supersededAt',
    'supersededBy',
    'supersededById',
    'urgency',
    'withdrawnAt',
    'withdrawnBy',
    'withdrawnNote',
  ],
  indexes: [
    { name: 'ruling_ruledAt_idx', columns: ['ruledAt'] },
    { name: 'ruling_supersededById_idx', columns: ['supersededById'] },
    { name: 'ruling_requesterAgentId_idx', columns: ['requesterAgentId'] },
    { name: 'ruling_ruledByAgentId_idx', columns: ['ruledByAgentId'] },
    { name: 'ruling_answerChoiceId_idx', columns: ['answerChoiceId'] },
  ],
  summary:
    'Recreates table ruling to apply schema changes: database/ruling/foreign-key:ruledByAgentId->.agent(id)',
  postchecks: [
    {
      description: 'verify foreign key (requesterAgentId) → agent(id) on "ruling"',
      sql: "SELECT EXISTS (SELECT 1 FROM pragma_foreign_key_list('ruling') f WHERE f.\"table\" = 'agent' GROUP BY f.id HAVING COUNT(*) = 1 AND SUM(CASE WHEN (f.\"from\", f.\"to\") IN (('requesterAgentId', 'id')) THEN 1 ELSE 0 END) = 1)",
    },
    {
      description: 'verify foreign key (ruledByAgentId) → agent(id) on "ruling"',
      sql: "SELECT EXISTS (SELECT 1 FROM pragma_foreign_key_list('ruling') f WHERE f.\"table\" = 'agent' GROUP BY f.id HAVING COUNT(*) = 1 AND SUM(CASE WHEN (f.\"from\", f.\"to\") IN (('ruledByAgentId', 'id')) THEN 1 ELSE 0 END) = 1)",
    },
    {
      description: 'verify foreign key (answerChoiceId) → rulingChoice(id) on "ruling"',
      sql: "SELECT EXISTS (SELECT 1 FROM pragma_foreign_key_list('ruling') f WHERE f.\"table\" = 'rulingChoice' GROUP BY f.id HAVING COUNT(*) = 1 AND SUM(CASE WHEN (f.\"from\", f.\"to\") IN (('answerChoiceId', 'id')) THEN 1 ELSE 0 END) = 1)",
    },
    {
      description: 'verify foreign key (supersededById) → ruling(id) on "ruling"',
      sql: "SELECT EXISTS (SELECT 1 FROM pragma_foreign_key_list('ruling') f WHERE f.\"table\" = 'ruling' GROUP BY f.id HAVING COUNT(*) = 1 AND SUM(CASE WHEN (f.\"from\", f.\"to\") IN (('supersededById', 'id')) THEN 1 ELSE 0 END) = 1)",
    },
  ],
  operationClass: 'destructive',
};
