import { col, fn, primaryKey, unique } from '@prisma-next/sqlite/migration';

export const CHANGES_TABLES = [
  {
    table: 'change',
    columns: [
      col('activityAt', 'TEXT', { notNull: true }),
      col('baseRef', 'TEXT', { notNull: true }),
      col('body', 'TEXT', { notNull: true }),
      col('checks', 'TEXT', { notNull: true }),
      col('createdAt', 'TEXT', { notNull: true, default: fn('now()') }),
      col('draftAt', 'TEXT'),
      col('externalId', 'TEXT'),
      col('headRef', 'TEXT', { notNull: true }),
      col('headSha', 'TEXT'),
      col('host', 'TEXT', { notNull: true }),
      col('id', 'TEXT', { notNull: true }),
      col('landedAt', 'TEXT'),
      col('mergeable', 'TEXT', { notNull: true }),
      col('observedAt', 'TEXT', { notNull: true }),
      col('openedByAgentId', 'TEXT'),
      col('originSessionId', 'TEXT'),
      col('preparedHeadRef', 'TEXT'),
      col('preparedHeadSha', 'TEXT'),
      col('proposalFrozenAt', 'TEXT'),
      col('raw', 'TEXT'),
      col('repoId', 'TEXT', { notNull: true }),
      col('review', 'TEXT', { notNull: true }),
      col('stage', 'TEXT', { notNull: true }),
      col('submissionKey', 'TEXT'),
      col('title', 'TEXT', { notNull: true }),
      col('url', 'TEXT'),
      col('withdrawnAt', 'TEXT'),
      col('workingDiff', 'TEXT'),
      col('workingTreeStatus', 'TEXT'),
      col('worktreePath', 'TEXT'),
    ],
    constraints: [
      primaryKey(['id']),
      unique(['submissionKey']),
      unique(['host', 'repoId', 'externalId']),
    ],
  },
  {
    table: 'changeTransition',
    columns: [
      col('activityAt', 'TEXT', { notNull: true }),
      col('changeId', 'TEXT', { notNull: true }),
      col('fromStage', 'TEXT', { notNull: true }),
      col('id', 'TEXT', { notNull: true }),
      col('observedAt', 'TEXT', { notNull: true }),
      col('toStage', 'TEXT', { notNull: true }),
    ],
    constraints: [primaryKey(['id'])],
  },
  {
    table: 'changeVerdict',
    columns: [
      col('changeId', 'TEXT', { notNull: true }),
      col('landedAt', 'TEXT', { notNull: true, default: fn('now()') }),
      col('verdict', 'TEXT', { notNull: true }),
    ],
    constraints: [primaryKey(['changeId'])],
  },
  {
    table: 'repo',
    columns: [
      col('createdAt', 'TEXT', { notNull: true, default: fn('now()') }),
      col('defaultRef', 'TEXT', { notNull: true }),
      col('id', 'TEXT', { notNull: true }),
      col('name', 'TEXT', { notNull: true }),
      col('source', 'TEXT', { notNull: true }),
    ],
    constraints: [primaryKey(['id']), unique(['source'])],
  },
  {
    table: 'berth',
    columns: [
      col('agentId', 'TEXT', { notNull: true }),
      col('branch', 'TEXT', { notNull: true }),
      col('createdAt', 'TEXT', { notNull: true, default: fn('now()') }),
      col('id', 'TEXT', { notNull: true }),
      col('path', 'TEXT', { notNull: true }),
      col('reclaimState', 'TEXT'),
      col('ref', 'TEXT', { notNull: true }),
      col('runner', 'TEXT', { notNull: true }),
      col('slug', 'TEXT', { notNull: true }),
      col('source', 'TEXT', { notNull: true }),
      col('status', 'TEXT', { notNull: true }),
      col('strandedAt', 'TEXT'),
      col('updatedAt', 'TEXT', { notNull: true, default: fn('now()') }),
    ],
    constraints: [primaryKey(['id'])],
  },
  {
    table: 'moorage',
    columns: [
      col('agentId', 'TEXT', { notNull: true }),
      col('createdAt', 'TEXT', { notNull: true, default: fn('now()') }),
      col('reclaimState', 'TEXT'),
      col('root', 'TEXT', { notNull: true }),
      col('runner', 'TEXT', { notNull: true }),
      col('status', 'TEXT', { notNull: true }),
      col('updatedAt', 'TEXT', { notNull: true, default: fn('now()') }),
    ],
    constraints: [primaryKey(['agentId'])],
  },
];
